apiVersion: v1
kind: Secret
metadata:
  name: debproxy-keys
  namespace: debproxy
type: Opaque
stringData:
  debproxy.asc: |
    -----BEGIN PGP PRIVATE KEY BLOCK-----
    REPLACE_ME
    -----END PGP PRIVATE KEY BLOCK-----
  debian-archive.asc: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    REPLACE_ME
    -----END PGP PUBLIC KEY BLOCK-----
