apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: debproxy
  namespace: debproxy
  labels:
    app: debproxy
spec:
  selector:
    matchLabels:
      app: debproxy
  endpoints:
    - port: metrics
      path: /metrics
